OPENAI_API_KEY = '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'

[connections.stocks_db]
url = "sqlite:///stocks.db"

[connections.local]
url = "mysql://me:****@localhost:3306/local_db"

[connections.staging]
url = "mysql://jdoe:******@staging.acmecorp.com:3306/staging_db"

